#!/usr/bin/env bash
set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export GAUENV_DEBUG=1
  shift
fi

if [ -n "$GAUENV_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "gauenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${GAUENV_ROOT}" ]; then
  GAUENV_ROOT="${HOME}/.gauenv"
else
  GAUENV_ROOT="${GAUENV_ROOT%/}"
fi
export GAUENV_ROOT

if [ -z "${GAUENV_DIR}" ]; then
  GAUENV_DIR="$(pwd)"
else
  cd "$GAUENV_DIR" 2>/dev/null || {
    echo "gauenv: cannot change working directory to \`$GAUENV_DIR'"
    exit 1
  } >&2
  GAUENV_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export GAUENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${GAUENV_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

hook_path="${GAUENV_HOOK_PATH}:${GAUENV_ROOT}/gauenv.d:/usr/local/etc/gauenv.d:/etc/gauenv.d:/usr/lib/gauenv/hooks"
for plugin_hook in "${GAUENV_ROOT}/plugins/"*/etc/gauenv.d; do
  hook_path="${hook_path}:${plugin_hook}"
done
export GAUENV_HOOK_PATH="$hook_path"

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(gauenv---version)\n$(gauenv-help)" >&2
  ;;
"-v" )
  exec gauenv---version
  ;;
* )
  command_path="$(command -v "gauenv-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "gauenv: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
