#!/usr/bin/env bash
# Summary: Display prefix for a Gauche version
# Usage: gauenv prefix [<version>]
#
# Displays the directory where a Gauche version is installed. If no
# version is given, `gauenv prefix' displays the location of the
# currently selected version.

set -e
[ -n "$GAUENV_DEBUG" ] && set -x

# Provide gauenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec gauenv-versions --bare
fi

if [ -n "$1" ]; then
  export GAUENV_VERSION="$1"
elif [ -z "$GAUENV_VERSION" ]; then
  GAUENV_VERSION="$(gauenv-version-name)"
fi

if [ "$GAUENV_VERSION" = "system" ]; then
  GAUCHE_PATH="$(gauenv-which gosh)"
  GAUCHE_PATH="${GAUCHE_PATH%/*}"
  echo "${GAUCHE_PATH%/bin}"
  exit
fi

GAUENV_PREFIX_PATH="${GAUENV_ROOT}/versions/${GAUENV_VERSION}"
if [ ! -d "$GAUENV_PREFIX_PATH" ]; then
  echo "gauenv: version \`${GAUENV_VERSION}' not installed" >&2
  exit 1
fi

echo "$GAUENV_PREFIX_PATH"
