#!/usr/bin/env bash
# Summary: Explain how the current Gauche version is set
set -e
[ -n "$GAUENV_DEBUG" ] && set -x

if [ -n "$GAUENV_VERSION" ]; then
  echo "GAUENV_VERSION environment variable"
else
  gauenv-version-file
fi
