#!/usr/bin/env bash
# Summary: List existing gauenv shims
# Usage: gauenv shims [--short]

set -e
[ -n "$GAUENV_DEBUG" ] && set -x

# Provide gauenv completions
if [ "$1" = "--complete" ]; then
  echo --short
  exit
fi

shopt -s nullglob

for command in "${GAUENV_ROOT}/shims/"*; do
  if [ "$1" = "--short" ]; then
    echo "${command##*/}"
  else
    echo "$command"
  fi
done | sort
