#!/usr/bin/env bash
# Usage: gauenv completions <command> [arg1 arg2...]

set -e
[ -n "$GAUENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  gauenv-help --usage completions >&2
  exit 1
fi

COMMAND_PATH="$(command -v "gauenv-$COMMAND" || command -v "gauenv-sh-$COMMAND")"
if grep -i "^\([#%]\|--\|//\) provide gauenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
