#!/usr/bin/env bash
# Summary: Detect the file that sets the current gauenv version
set -e
[ -n "$GAUENV_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.gauche-version" ]; then
      echo "${root}/.gauche-version"
      exit
    elif [ -e "${root}/.gauenv-version" ]; then
      echo "${root}/.gauenv-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$GAUENV_DIR"
[ "$GAUENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${GAUENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${GAUENV_ROOT}/global" ]; then
  echo "${GAUENV_ROOT}/global"
elif [ -e "${GAUENV_ROOT}/default" ]; then
  echo "${GAUENV_ROOT}/default"
else
  echo "$global_version_file"
fi
