#!/usr/bin/env bash
# Summary: List all Gauche versions available to gauenv
# Usage: gauenv versions [--bare]
#
# Lists all Gauche versions found in `$GAUENV_ROOT/versions/*'.

set -e
[ -n "$GAUENV_DEBUG" ] && set -x

if [ "$1" = "--bare" ]; then
  hit_prefix=""
  miss_prefix=""
  current_version=""
  include_system=""
else
  hit_prefix="* "
  miss_prefix="  "
  current_version="$(gauenv-version-name || true)"
  include_system="1"
fi

print_version() {
  if [ "$1" == "$current_version" ]; then
    echo "${hit_prefix}$(gauenv-version 2>/dev/null)"
  else
    echo "${miss_prefix}$1"
  fi
}

# Include "system" in the non-bare output, if it exists
if [ -n "$include_system" ] && GAUENV_VERSION=system gauenv-which ruby >/dev/null 2>&1; then
  print_version system
fi

for path in "${GAUENV_ROOT}/versions/"*; do
  if [ -d "$path" ]; then
    print_version "${path##*/}"
  fi
done
