#!/usr/bin/env bash
#
# Summary: Set or show the shell-specific Gauche version
#
# Usage: gauenv shell <version>
#        gauenv shell --unset
#
# Sets a shell-specific Gauche version by setting the `GAUENV_VERSION'
# environment variable in your shell. This version overrides local
# application-specific versions and the global version.
#
# <version> should be a string matching a Gauche version known to gauenv.
# The special version string `system' will use your default system Gauche.
# Run `gauenv versions' for a list of available Gauche versions.

set -e
[ -n "$GAUENV_DEBUG" ] && set -x

# Provide gauenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec gauenv-versions --bare
fi

version="$1"

if [ -z "$version" ]; then
  if [ -z "$GAUENV_VERSION" ]; then
    echo "gauenv: no shell-specific version configured" >&2
    exit 1
  else
    echo "echo \"\$GAUENV_VERSION\""
    exit
  fi
fi

if [ "$version" = "--unset" ]; then
  echo "unset GAUENV_VERSION"
  exit
fi

# Make sure the specified version is installed.
if gauenv-prefix "$version" >/dev/null; then
  echo "export GAUENV_VERSION=\"${version}\""
else
  echo "return 1"
  exit 1
fi
