#!/usr/bin/env bash
# Summary: Show the current Gauche version and its origin
#
# Shows the currently selected Gauche version and how it was
# selected. To obtain only the version string, use `gauenv
# version-name'.

set -e
[ -n "$GAUENV_DEBUG" ] && set -x

echo "$(gauenv-version-name) (set by $(gauenv-version-origin))"
