#!/usr/bin/env bash
# Summary: Show the current Gauche version
set -e
[ -n "$GAUENV_DEBUG" ] && set -x

if [ -z "$GAUENV_VERSION" ]; then
  GAUENV_VERSION_FILE="$(gauenv-version-file)"
  GAUENV_VERSION="$(gauenv-version-file-read "$GAUENV_VERSION_FILE" || true)"
fi

if [ -z "$GAUENV_VERSION" ] || [ "$GAUENV_VERSION" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "${GAUENV_ROOT}/versions/${version}" ]
}

if version_exists "$GAUENV_VERSION"; then
  echo "$GAUENV_VERSION"
elif version_exists "${GAUENV_VERSION#gauche-}"; then
  { echo "warning: ignoring extraneous \`gauche-' prefix in version \`${GAUENV_VERSION}'"
    echo "         (set by $(gauenv-version-origin))"
  } >&2
  echo "${GAUENV_VERSION#gauche-}"
else
  echo "gauenv: version \`$GAUENV_VERSION' is not installed" >&2
  exit 1
fi
