#!/usr/bin/env bash
#
# Summary: Display the full path to an executable
#
# Usage: gauenv which <command>
#
# Displays the full path to the executable that gauenv will invoke when
# you run the given command.

set -e
[ -n "$GAUENV_DEBUG" ] && set -x

# Provide gauenv completions
if [ "$1" = "--complete" ]; then
  exec gauenv shims --short
fi

expand_path() {
  if [ ! -d "$1" ]; then
    return 1
  fi

  local cwd="$(pwd)"
  cd "$1"
  pwd
  cd "$cwd"
}

remove_from_path() {
  local path_to_remove="$(expand_path "$1")"
  local result=""

  if [ -z "$path_to_remove" ]; then
    echo "${PATH}"
    return
  fi

  local paths
  IFS=: paths=($PATH)

  for path in "${paths[@]}"; do
    path="$(expand_path "$path" || true)"
    if [ -n "$path" ] && [ "$path" != "$path_to_remove" ]; then
      result="${result}${path}:"
    fi
  done

  echo "${result%:}"
}

GAUENV_VERSION="$(gauenv-version-name)"
GAUENV_COMMAND="$1"

if [ -z "$GAUENV_COMMAND" ]; then
  gauenv-help --usage which >&2
  exit 1
fi

if [ "$GAUENV_VERSION" = "system" ]; then
  PATH="$(remove_from_path "${GAUENV_ROOT}/shims")"
  GAUENV_COMMAND_PATH="$(command -v "$GAUENV_COMMAND" || true)"
else
  GAUENV_COMMAND_PATH="${GAUENV_ROOT}/versions/${GAUENV_VERSION}/bin/${GAUENV_COMMAND}"
fi

OLDIFS="$IFS"
IFS=$'\n' scripts=(`gauenv-hooks which`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

if [ -x "$GAUENV_COMMAND_PATH" ]; then
  echo "$GAUENV_COMMAND_PATH"
else
  echo "gauenv: $GAUENV_COMMAND: command not found" >&2

  versions="$(gauenv-whence "$GAUENV_COMMAND" || true)"
  if [ -n "$versions" ]; then
    { echo
      echo "The \`$1' command exists in these Gauche versions:"
      echo "$versions" | sed 's/^/  /g'
      echo
    } >&2
  fi

  exit 127
fi
