#!/usr/bin/env bash
set -e
[ -n "$GAUENV_DEBUG" ] && set -x

# Provide gauenv completions
if [ "$1" = "--complete" ]; then
  exec gauenv-rehash --complete
fi

# When gauenv shell integration is enabled, delegate to gauenv-rehash,
# then tell the shell to empty its command lookup cache.
gauenv-rehash
echo "hash -r 2>/dev/null || true"
